name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/nbdev-ci@master]
  test_teaxyz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: teaxyz/setup@v0
    - name: test
      run: |
        which pip
        tea which pip
        tea pip install nbdev
        tea nbdev_test
  # pypi:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
